//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookComment()
        {
            this.BookRelpy = new HashSet<BookRelpy>();
        }
    
        public int BookCommentID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public string Comment_Content { get; set; }
        public Nullable<System.DateTime> Comment_Time { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookRelpy> BookRelpy { get; set; }
    }
}
